site_name: SleepKit
site_dir: "site"
site_url: "https://ambiqai.github.io/sleepkit"
site_description: SleepKit, perform AI-based sleep monitoring tasks
repo_name: AmbiqAI/sleepkit
repo_url: https://github.com/AmbiqAI/sleepkit
copyright: Copyright &copy; 2023 Ambiq

nav:
  - Home:
    - Home: index.md
    - Quickstart: quickstart.md
    - Modes:
      - modes/index.md
      - Download: modes/download.md
      - Feature: features/index.md
      - Train: modes/train.md
      - Evaluate: modes/evaluate.md
      - Export: modes/export.md
      - Demo: modes/demo.md
    - Tasks:
      - tasks/index.md
      - Detect: tasks/detect.md
      - Stage: tasks/stage.md
      - Apnea: tasks/apnea.md
      - BYOT: tasks/byot.md
    - Datasets:
      - datasets/index.md
    - Features:
      - features/index.md
    - Models:
      - models/index.md
    - Model Zoo:
      - zoo/index.md
    - Guides:
      - guides/index.md
    - API: api/

  - Quickstart:
    - quickstart.md
    - Usage:
      - CLI: usage/cli.md
      - Python: usage/python.md

  - Tasks:
    - tasks/index.md
    - Detect: tasks/detect.md
    - Stage: tasks/stage.md
    - Apnea: tasks/apnea.md
    - BYOT: tasks/byot.md

  - Modes:
    - modes/index.md
    - Configuration: modes/configuration.md
    - Download: modes/download.md
    - Feature: features/index.md
    - Train: modes/train.md
    - Evaluate: modes/evaluate.md
    - Export: modes/export.md
    - Demo: modes/demo.md

  - Datasets:
    - datasets/index.md
    - CMIDSS: datasets/cmidss.md
    - MESA: datasets/mesa.md
    - YSYW: datasets/ysyw.md
    - STAGES: datasets/stages.md
    - Synthetic: datasets/synthetic.md
    - BYOD: datasets/byod.md

  - Features:
    - features/index.md
    - FS-W-PA-14: features/fs_w_pa_14.md
    - FS-C-EAR-9: features/fs_c_ear_9.md
    - FS-W-A-5: features/fs_w_a_5.md
    - FS-H-E-10: features/fs_h_e_10.md
    - FS-W-P-5: features/fs_w_p_5.md
    - BYOFS: features/byofs.md

  - Models:
    - models/index.md
    - BYOM: models/byom.md

  - Model Zoo:
    - zoo/index.md
    - Detect: zoo/detect.md
    - Stage: zoo/stage.md
    - Apnea: zoo/apnea.md

  - Guides:
    - guides/index.md
    - "Sleep Staging Ablation": guides/stage-ablation.md
    - "Train Sleep Detection": guides/train-detect-model.md

  - API: api/

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo-white.png
  icon:
      repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Use system theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark theme
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections  # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously

plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          options:
            show_bases: false
            docstring_style: google
            docstring_section_style: list
            line_length: 120
            show_root_heading: false
            heading_level: 2
            merge_init_into_class: true
            show_root_full_path: false
            parameter_headings: true
            show_symbol_type_heading: true
            group_by_category: true
            show_category_heading: true
            modernize_annotations: true
            members_order: source
            filters: ["!^_", "^__init__$"]
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            show_docstring_attributes: true
            show_source: true

  - mkdocs-jupyter:
      include_requirejs: true
      include_source: true

extra_css:
  - css/mkdocstrings.css
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
  - https://cdn.plot.ly/plotly-2.33.0.min.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - md_in_html
  - sane_lists
